### ISSUE TITLE
Bug: User's Info Not Displaying on Profile Page 

### ISSUE THREAD

**Issue by HarshadaGirase** [Manishkr1007/WordWeaver#15]
Description:- 
The user's profile page on Word Weaver is not displaying the essential information such as ID, Name, and Email. The fields are visible but remain empty, which affects the user experience and functionality.

Steps to Reproduce:
Log in to Word Weaver with a registered user account.
Navigate to the user profile page.
Observe that the ID, Name, and Email fields are empty.

Expected Behavior:
The user's profile page should display the relevant details, including:

User ID
Name
Email address

Actual Behavior:
The profile page loads but does not populate any user information in the designated fields (ID, Name, Email). These sections remain empty despite being logged in

![userinfo](https://github.com/user-attachments/assets/f78febcf-bf71-4c75-9f7c-8fe5378fb5b5)

**Comment by shreyamaheshwari1** [comment]
@Manishkr1007 could you please assign me this issue . I can fix this
