### ISSUE TITLE
User profile section 

### ISSUE THREAD

**Issue by idk-mr4tyunjay** [Manishkr1007/WordWeaver#4]
The user profile section is currently non-functional and needs to be fixed. Users are unable to access or update their profiles

![Screenshot 2024-10-01 200016](https://github.com/user-attachments/assets/f674d034-2176-4ded-a341-35a398d765d3)

Tasks:

- Investigate the cause of the profile section malfunction (e.g., UI not rendering, API failures, or navigation issues).
- Ensure that the profile data is properly loaded and displayed to users.
- Add functionality for updating user details and saving changes.

@Manishkr1007 can you assign this issue to me?

**Comment by gurramkarthiknetha** [comment]
I want to take this up this issue if you are not solving...

**Comment by idk-mr4tyunjay** [comment]
@gurramkarthiknetha If i don't close it today you can solve it
