### ISSUE TITLE
Enhancement: Improve Footer Design for Better User Experience

### ISSUE THREAD

**Issue by amanver45** [Manishkr1007/WordWeaver#60]
The current footer design can be enhanced to improve both its visual appeal and usability. Here are a few proposed changes:

1.*Improve Text Readability:* The font size under the "SUPPORT" and "LEGALS" sections is small and could be increased for better readability. Improving the contrast between the text and background will also help.
2*Add Social Media Icons:* The footer currently lacks social media links. Adding icons for platforms like Twitter, LinkedIn, or Instagram would modernize the design and enhance user engagement.
3*Add More Spacing: *The footer feels slightly cramped. Increasing the spacing and padding between sections will provide a cleaner, more structured layout.
4*Introduce New Sections:* Consider adding sections like:
a)Newsletter sign-up
b)Quick links for easier navigation
5*Enhance Copyright Section:* The copyright text could be slightly reduced in font size or placed more subtly to minimize clutter.

These enhancements aim to make the footer more functional, aesthetically pleasing, and user-friendly.

**Comment by GLITCH-in-MATRIX9** [comment]
Please assign me this issue.I'd love to work upon the readability of this issue.

**Comment by gurramkarthiknetha** [comment]
I want to take this up this issue if you are not solving...

**Comment by amanver45** [comment]
@Manishkr1007  can i work on this issue?
