### ISSUE TITLE
add Contributing.md file

### ISSUE THREAD

**Issue by Amulya-B28** [Manishkr1007/WordWeaver#65]
I would like to add this file because it is a crucial document in open-source repositories, providing clear guidelines and instructions for anyone interested in contributing to the project. It outlines how contributors can get involved, the contribution process, and the repository's coding standards and rules. Please assign this task to me.

**Comment by shauryaq05** [comment]
It's crucial part in laying clear principles and foundations while contributing to the project. Please assign this task to  me.
